config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'stace', to: 'pages#stace'
  get 'westfield', to: 'pages#westfield'
  get 'oktra', to: 'pages#oktra'
  # complete routes one by one, so you understand how they need to be coded. could use resources :articles to get them all
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  # the below ensures that all paths are set up except the new which is set up above
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
end

app/models/Article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
# articles wont save if they dont meet the validations above

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, presence: true,
            uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  # regex below is standard for email. check it works in rubular.com
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false }, length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  # this is for bcrypt gem. uncomment in gem file, run bundle install in terminal and then write the below
  # has_secure_password
end
# 136 add secure password approx 13:20

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

# performs this action before anything else on this page where set article is used
# write this code once the controller has been coded and you can see what has the same code
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
     # uses the before action above and set_article below
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    # uses the before action above and set_article below
  end

  def create
    # to create you need top level article, and the only permitted attributes are title and description
    @article = Article.new(article_params)
    @article.user = User.first
    # save back to the database
    if @article.save
      # shows user that the article has been saved. see application.html for each method
      flash[:notice] = "Article was created sucessfully!"
    # now redirect to articles show page, so you can see its been added. check with rails c that it is in database. Article.all
    # check routes. it says article/:id, so it would be as below
      redirect_to (@article)
    else
      # if it doesnt work, we need to re render the form to fill out again
      render 'new'
    end
  end

  def update
     # uses the before action above and set_article below
    # will only update if the below requirements are met
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      # redirects to article show page
      redirect_to @article
    else
      # if not filled in properly, the edit form will be rendered again so that user has to resubmit
      render 'edit'
    end
  end

  def destroy
    # first, have to find the article to destroy
     # uses the before action above and set_article below
    @article.destroy
    redirect_to articles_path
  end

  # only for use inside this controller
  private

  def set_article
    # the below line is used in destroy, update, edit and show. to make DRY, converted to one line
    @article = Article.find(params[:id])
  end

  def article_params
    # below taken from update and create, so that users have to use the required permissions
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfull created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def stace
  end

  def westfield
  end

  def oktra
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "your account information was success"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "welcome, #{@user.username} you have successfully signed up!"
      redirect_to articles_path
    else
      render 'new'
    end
  end



  private

  def user_params
    params.require(:user).permit(:username, :email, :password_digest)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">listing all articles, yo</h1>
  <div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by  <%= article.user.username if article.user%>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <p class="btn btn-outline-success"><%= link_to 'View', article_path(article) %></p>
            <p class="btn btn-outline-info"><%= link_to 'Edit', edit_article_path(article) %></p>
            <p class="btn btn-outline-danger"><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "are you sure?" } %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at)%>,
            edited <%= time_ago_in_words(article.updated_at) %></small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
  <h1 class="text-center mt-4">Create a new article</h1>
  <%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
          by  <%= @article.user.username if @article.user%>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <p class="btn btn-outline-info"><%= link_to 'Edit', edit_article_path(@article) %></p>
            <p class="btn btn-outline-danger"><%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "are you sure?" } %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at)%>,
            edited <%= time_ago_in_words(@article.updated_at) %></small>
          </div>
        </div>
      </div>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>

  <div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-outline-light btn-lg" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class = "container">
 <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at)%>,
            edited <%= time_ago_in_words(category.updated_at) %></small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
 <h1 class="text-center mt-4">create a new category</h1>

  <!-- the form is the same for the new and edit, so it can be used as a partial -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
  <!-- this ensures that the form shows the existing information of the article, so can edit -->
  <!-- it looks at which model. we use the instance variable -->
    <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local:true) do |f| %>
      <div class="form-group row">
        <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
        <div class="col-10">
        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "enter a name" %>
        </div>
      </div>

      <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg"%>
      </div>
    <% end %>
    </div>
    <div class="mb-3">
      <div class= "btn btn-outline-dark btn-lg"><%= link_to ' Return to article listings', articles_path, class: "text-info" %>
    </div>
      </div>
  </div>
</div>

app/views/categories/show.html.erb
 <h1 class="text-center mt-4">Category: <%= @category.name %></h1>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg|  %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CamsBlog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class= "d-flex flex-column">
    <%= render 'shared/navbar' %>
    <div class="page-content">
    <!-- renders the partial created. no _ needed -->
    <%= render 'layouts/messages' %>
  <!-- yields to other html pages to load -->
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container" id="about-container">
  <div class="card-product">
    <p><%= image_tag "cam.jpg" %></p>
    <div class="card-product-infos">
      <h1>Hey, I'm Cam</h1>
      <p>After 9 years of working in construction, I decided to change my career</p>
      <p>I have just completed a very intensive 9 week, Full Stack Developer, bootcamp with Le Wagon.
      Now I'm going it alone and attempting to build my own products without the ability to ask teachers for help...</p>
      <p>This website will serve to show my experience and my continued development, self learning</p>
      <p><strong>Below</strong> you'll find a breakdown of my pre-tech career</p>
    </div>
  </div>


  <h2 class="text-center mt-4">My career so far</h2>

  <div class="card-category">
    <p class="btn btn-outline-info"><%= link_to 'Stace', stace_path %></p>
    <%= image_tag "stace1.jpeg" %>
  </div>
  <div class="card-category">
    <p class="btn btn-outline-info"><%= link_to 'Westfield', westfield_path %></p>
    <%= image_tag "" %>
  </div>
  <div class="card-category">
    <p class="btn btn-outline-info"><%= link_to 'Oktra', oktra_path %></p>
    <%= image_tag "" %>
  </div>

</div>

app/views/pages/home.html.erb
  <div class="container" id="home-container">
    <div class="jumbotron text-center">
      <h1 id="home-title" class="display-4">Cam's coding blog!</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%= link_to "Sign Up!", signup_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>





<!-- 144. tues 15. -->

app/views/pages/oktra.html.erb
<h1>oktra</h1>

app/views/pages/stace.html.erb
<h1>Stace</h1>

<p class="btn btn-outline-info"><%= link_to 'Back to profile', about_path %></p>

app/views/pages/westfield.html.erb
<h1>westfield</h1>

app/views/shared/_errors.html.erb
<!-- checks if any errors in form submission. then shows error messages to user-->
<!-- if blank and/or too short, user will be prompted - based on validations -->
  <% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<!-- footer -->
<div id="sticky-footer" class="footer fixed-bottom bg-dark text-white">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagondsss
  </div>
</div>

app/views/shared/_navbar.html.erb
 <!-- navbar -->
 <nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "CAM'S BLOG", root_path, class: "navbar-brand", id:"blog"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Portfolio PLACEHOLDER</a>
          </li>
          <li class="nav-item">
            <%= link_to 'About Me', about_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Create New Article", new_article_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All Articles", articles_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Categories", categories_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "New Category", new_category_path, class: "nav-link" %>
          </li>

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/users/_form.html.erb
<!-- the form is the same for the new and edit, so it can be used as a partial -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
  <!-- this ensures that the form shows the existing information of the article, so can edit -->
  <!-- it looks at which model. we use the instance variable -->
    <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local:true) do |f| %>
      <div class="form-group row">
        <%= f.label :username, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "enter your username" %>
        </div>
      </div>


      <div class="form-group row">
        <%= f.label :email, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "enter email here"%>
        </div>
      </div>

       <div class="form-group row">
        <%= f.label :password, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "enter password here"%>
        </div>
      </div>

      <div class="form-group row justify-content-center">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg")%>
      </div>
    <% end %>
    </div>
    <div class="mb-3">
      <div class= "btn btn-outline-dark btn-lg"><%= link_to ' Return to article listings', articles_path, class: "text-info" %>
    </div>
      </div>
  </div>
</div>

app/views/users/edit.html.erb
 <h1 class="text-center mt-4">Edit your profile</h1>
  <%= render 'form' %>

app/views/users/new.html.erb
 <h1 class="text-center mt-4">Sign up for Cam's blog</h1>
  <%= render 'form' %>

app/views/users/show.html.erb
 <h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>



<%= render 'articles/article' %>